version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  deploy-frontend:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}'
          aws-region: AWS_DEFAULT_REGION
          profile-name: ${AWS_ROLE}
          role-session-name: CircleSession
          session-duration: '1800'
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: "${AWS_CLUSTER_NAME}"
          cluster-authentication-role-arn: arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}
      - run:
          name: Create and push frontend container
          command: |
              docker build -t app/usct/dev-ui:latest .
              aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 463471358064.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
              docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app/usct/dev-ui:latest

parameters:
  deploy_allowed:
    type: boolean
    default: false

workflows:
  Frontend Deployment:
    when: << pipeline.parameters.deploy_allowed >>
    jobs:
      - hold:
          type: approval
      - deploy-frontend:
          context: aws
          requires:
            - hold
