playground_frontend:
  name: "frontend"
  replicaCount: 1
  labels: 
    app: "frontend"
  template:
    labels: 
      app: "frontend"
  container:
    name: frontend
    image: 161826879607.dkr.ecr.eu-central-1.amazonaws.com/app/usct/plg-ui
    imageTag: latest
    imagePullPolicy: "Always"
  profiles: "container"
  service:
    name: "frontend"
    type: ClusterIP
    port: 8080
    targetPort: 8080